
services:
  logging-service:
    build:
      context: ../logging-service
      dockerfile: Dockerfile
    networks:
      - shared-network
    container_name: logging-service
    
  main-app:
    build:
      context: ../main-app
      dockerfile: Dockerfile
    container_name: main-app
    networks:
      - shared-network
    depends_on:
      - auth-service
    ports:
      - "8080:8080"

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    networks:
      - shared-network
    depends_on:
      - logging-service

networks:
  shared-network:
    external: true
      